#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("QuestionsNewAndroid.Resource", IsApplication=true)]

namespace QuestionsNewAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::QuestionsNew.Core.Resource.String.library_name = global::QuestionsNewAndroid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_overflow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int addQuestion = 2131099664;
			
			// aapt resource value: 0x7f060021
			public const int answerQuestions = 2131099681;
			
			// aapt resource value: 0x7f060019
			public const int answerText = 2131099673;
			
			// aapt resource value: 0x7f06001d
			public const int answersView = 2131099677;
			
			// aapt resource value: 0x7f060003
			public const int cancel = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int cancelButton = 2131099659;
			
			// aapt resource value: 0x7f06001a
			public const int dateAnswered = 2131099674;
			
			// aapt resource value: 0x7f060024
			public const int deleteGroup = 2131099684;
			
			// aapt resource value: 0x7f060022
			public const int editAddQuestions = 2131099682;
			
			// aapt resource value: 0x7f060009
			public const int editAnswer = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int editGroupName = 2131099662;
			
			// aapt resource value: 0x7f060018
			public const int editQuestion = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int groupListView = 2131099670;
			
			// aapt resource value: 0x7f06001c
			public const int groupName = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int imageInfo = 2131099675;
			
			// aapt resource value: 0x7f060014
			public const int imageMenu = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int linearClick = 2131099666;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout2 = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int linearLayout3 = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout4 = 2131099656;
			
			// aapt resource value: 0x7f060015
			public const int newGroupButton = 2131099669;
			
			// aapt resource value: 0x7f060000
			public const int questionGroupName = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int questionList = 2131099652;
			
			// aapt resource value: 0x7f060011
			public const int questionListView = 2131099665;
			
			// aapt resource value: 0x7f060007
			public const int questionText = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int relativeLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int save = 2131099650;
			
			// aapt resource value: 0x7f06000f
			public const int saveGroupName = 2131099663;
			
			// aapt resource value: 0x7f06000a
			public const int saveQuestionsButton = 2131099658;
			
			// aapt resource value: 0x7f060020
			public const int specificAnswerList = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int textAnswerDate = 2131099679;
			
			// aapt resource value: 0x7f060013
			public const int textGroupName = 2131099667;
			
			// aapt resource value: 0x7f06001e
			public const int textQuestionGroup = 2131099678;
			
			// aapt resource value: 0x7f06000c
			public const int textView1 = 2131099660;
			
			// aapt resource value: 0x7f060017
			public const int textView2 = 2131099671;
			
			// aapt resource value: 0x7f060023
			public const int viewAnswers = 2131099683;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Answer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AnswerView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CancelButton = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Group = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int GroupView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int QuestionView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SpecificAnswerListView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ViewAnswerListView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ViewAnswers = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ViewSpecificAnswer = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int questionGroupMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int dialog_cancel = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int dialog_two_buttons_title = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int dialog_yes = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
